apiVersion: v1
kind: Pod
metadata:
  name: taskly-database
  labels:
    app: taskly-database
spec:
  containers:
    - name: mongodb
      image: mongo:latest
      ports:
        - containerPort: 27017
      env:
        - name: MONGO_INITDB_DATABASE
          value: "taskly_app"
      volumeMounts:
        - name: mongo-data
          mountPath: /data/db
  volumes:
    - name: mongo-data
      emptyDir: {}
